### ISSUE TITLE
Your 70+ Patterns are wrong!

### ISSUE THREAD

**Issue by fuba82** [michaelschufi/poe-stash-regex-search#2]
Hi there, your 70+ Patterns are wrong.

example...

*70+ life*:
```
"(1?[7-9][0-9].+life)"
```
will **NOT** match values from 100 to 169, the correct pattern is:
```
"([1-9]\d{2,}|[7-9]\d).+life"
```
this will work from 70 to endless

---

for *75+ life* it is more complicated like this:
```
"([1-9]\d{2,}|[8-9]\d|[7][5-9]).+life"
```
but with this you can set any range you like!

---

and the *80+ item level*
```
"(item level: [8-9][0-9])"
```
this is actually 80-99 but in that case not important because there are no Item Level 99 is PoE :D

but the correct 80+ would be:
```
"item level: ([1-9]\d{2,}|[8-9]\d)"
```

maybe you can add correct this, **especially** the 70+ life!

greetings, fuba

**Comment by michaelschufi** [comment]
Thank you! I have updated it and closed this issue.
